### ISSUE TITLE
Don't give up! (The NO future of Spaghettis)

### ISSUE THREAD

**Issue by jacksonmgoode** [Spaghettis/Spaghettis#252]
I've been reading through your threads on pdpatchrepo and you've taken on a huge project but something that would be a massive improvement to a legacy platform (Pd) that has no clear successor (not Max).

I saw your post that the project is dead, if you're really think of abandoning it, I would at least pass it by Miller or Jonathan Wilkes to see if your improvements could help out in their projects. Otherwise I would love to see how Spaghettis progresses, even if it is at a slow pace!

**Comment by nicolasdanet** [comment]
First thanks for your feedback! The fact is that after about 5 years i have no more fun anymore.  I need holidays! Those repositories will remains there (at least readable). I'll still work slowly on it on my own, just for me (but i'm not sure i'll finish the job a day)! And TBH i'm not sure it will be public again.

< https://forum.pdpatchrepo.info/topic/12588/the-future-of-spaghettis/4 >

**Comment by nicolasdanet** [comment]
Reopen for thoughts and comments.
