### ISSUE TITLE
Patch cords are invisible

### ISSUE THREAD

**Issue by jacksonmgoode** [Spaghettis/Spaghettis#256]
<img width="412" alt="Screenshot 2020-10-13 at 17 39 34" src="https://user-images.githubusercontent.com/54308792/95883301-4c232c00-0d6a-11eb-9649-fe80f9d1ab9f.png">

Speaks for itself - and issue with Tk?

Latest build of Spaghettis - macOS 10.15.7

**Comment by jacksonmgoode** [comment]
I would also like to add (though this may be an unrelated issue) that the DPI appears to be off on my monitor as it looks fuzzy. The screenshot however looks clear oddly.

**Comment by nicolasdanet** [comment]
I can reproduce it. **It is a bug of Tk handling the macOS dark mode.** If you switch off the mode it should work ok. Can you confirm?

I don't know what to:
- Do nothing as i want to remove Tk in the (far away) futur.
- Wait an try to see if latests Tk fixed that.
- Add a workaround in the Tcl code if possible.

**Comment by nicolasdanet** [comment]
Note that Pd-0.51-2.app is working fine in dark mode, thus it should be possible also to use its version of Tk/Wish.

**Comment by nicolasdanet** [comment]
After quick investigations it seems that PureData simply disallow the dark mode.

< https://github.com/pure-data/pure-data/commit/2004496145e82a9cf960ceadccac620b7c82d100 >

Probably the best approach.

**Comment by nicolasdanet** [comment]
This approach seems to work fine: < https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app#2993818 >. Pull Request above.

**Comment by nicolasdanet** [comment]
Feel free to reopen the issue if the PR doesn't fix it.
