### ISSUE TITLE
Invalid samplerate - DSP cannot start

### ISSUE THREAD

**Issue by jacksonmgoode** [Spaghettis/Spaghettis#257]
<img width="420" alt="Screenshot 2020-10-13 at 17 41 30" src="https://user-images.githubusercontent.com/54308792/95883524-92788b00-0d6a-11eb-8284-aa27ab43ba26.png">

My default output is 44.1 Hz.

Latest build of Spaghettis - macOS 10.15.7

**Comment by nicolasdanet** [comment]
Is your built-in mircrophone also 44.1 Hz?

**Comment by jacksonmgoode** [comment]
Yes, it is. Let me know how I can test this.

**Comment by nicolasdanet** [comment]
You can download an compile this branch < https://github.com/nicolasdanet/Spaghettis/tree/hot >. The error message will report the detected samplig rate of the device if it is not equal to the required sampling rate.

Just an idea but have you athorize Spaghettis to access to your microphone?

**Comment by jacksonmgoode** [comment]
Yes, compiling and running that branch, as well as setting the mic to 44.1 Hz solves the issue!

![Screen Recording 2020-10-19 at 00 01 51](https://user-images.githubusercontent.com/54308792/96386907-031a1000-118e-11eb-96d5-7461773b0a52.gif)

**Comment by nicolasdanet** [comment]
I'll make more tests and i'll merge it soon.
