### ISSUE TITLE
Change readme.txt to Markdown

### ISSUE THREAD

**Issue by jacksonmgoode** [Spaghettis/Spaghettis#262]
This will allow the GitHub frontpage of the project to use Markdown formatting and the styling that GitHub adds to readme's.

**Comment by nicolasdanet** [comment]
I'm fond of old austere txt files.
I don't like at all the badges that people abuse (looking like balls on Christmas trees or jewelry on grannies).
But i promise i'll use markdown in the next README!

See: #261
