### ISSUE TITLE
Rewrite GEM based on a portable framework (OF, Cinder, ...)

### ISSUE THREAD

**Issue by nicolasdanet** [Spaghettis/Spaghettis#29]
## Expected Behavior

Somebody?

**Comment by nicolasdanet** [comment]
FYI: < https://github.com/cuinjune/ofxOfelia >

**Comment by dromer** [comment]
This is a grand idea. I approve!

**Comment by nicolasdanet** [comment]
Something like Ofelia < https://github.com/cuinjune/Ofelia >...

**Comment by 60-hz** [comment]
That's why I am trying to do with ofelia here
https://github.com/60-hz/Ofelia-Fast-Prototyping

Still learning lua / openframeworks... so anybody who can help would be very welcomed :)

**Comment by dromer** [comment]
I mostly know lua from openresty/nginx

**Comment by nicolasdanet** [comment]
I quickly learned Lua long time ago but i forgot it (such as Javascript, Ruby, Tcl...) since i only use C/C++ and a bit of Python for scripting. TBH i never used GEM nor Jitter (in Max/MSP) a lot. I"m mainly concern by music and composition. I was playing with machine learning when i started that fork, and since i was forced to understand all the DSP stuff. I would love in the future to find  somebody to help me for that feature (as i really can not be an expert in all the domains).
